language: go

go:
  - "1.11"
  - master

before_install:
  - go get -t -v ./...
  - go get -v golang.org/x/lint/golint
  - go get github.com/golang/dep/...

install:
  - $GOPATH/bin/dep ensure -v
script:
  - go test -v -race ./...
